#!/usr/bin/env bash
  2 # Transfers files from Holberton's client to another.
  3 # Accepts four arguments:
  4 #+    The path to file to be transferred.
  5 #+    The IP of server to transfer the file to.
  6 #+    The username that scp connects with.
  7 #+    The path to the SSH private key that scp uses.
  8 
  9 if [ $# -lt 4 ]
 10 then
 11   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
 12 else
 13   scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
 14 fi
