#!/usr/bin/env bash
# script that configures an Ubuntu server with the below requirements
cp /etc/hosts ~/hosts.new
sed -i 's/.*localhost$/127.0.0.2\tlocalhost/g' ~/hosts.new
sed -i '/.*facebook.com/d' ~/hosts.new
printf '8.8.8.8\tfacebook.com' >> ~/hosts.new
cp ~/hosts.new /etc/hosts
